version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: BookingHotelPostgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: unless-stopped

  backend:
    container_name: BookingHotelBackend
    build:
      context: .  # <-- Usa el Dockerfile en la raíz del proyecto
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres  # <-- Nombre del servicio de PostgreSQL
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "3000:3000"  # <-- Expone el puerto del backend
    depends_on:
      - postgres  # <-- Espera a que PostgreSQL esté listo
    restart: unless-stopped

volumes:
  postgres_data: